"""Transport-neutral voice event contracts."""

from olab_voice.transports.codec import pack_payload, unpack_payload
from olab_voice.transports.nats import NatsClient, NatsVoiceTransport
from olab_voice.transports.payloads import (
    PayloadStyle,
    audio_blob_from_payload,
    audio_blob_to_payload,
    transcript_event_from_payload,
    transcript_event_to_payload,
    tts_audio_from_payload,
    tts_audio_to_payload,
)
from olab_voice.transports.subjects import (
    GCS_AUDIO_COMMAND,
    GCS_AUDIO_RESPONSE,
    GCS_AUDIO_TRANSCRIBED,
    VOICE_AUDIO_BLOB,
    VOICE_AUDIO_FRAME,
    VOICE_COMMAND_WINDOW_CLOSED,
    VOICE_COMMAND_WINDOW_STARTED,
    VOICE_CONTROL,
    VOICE_RECIPIENT_REQUEST,
    VOICE_RECIPIENT_RESPONSE,
    VOICE_STATUS,
    VOICE_TRANSCRIPT_HYPOTHESIS,
    VOICE_TRANSCRIPT_INTERVAL_FINAL,
    VOICE_TRANSCRIPT_SEGMENT_FINAL,
    VOICE_TTS_AUDIO,
    VOICE_TTS_REQUEST,
    VOICE_WAKE_DETECTED,
    audio_blob_subject,
    transcript_subject,
    tts_audio_subject,
    voice_session_subject,
)

__all__ = [
    "GCS_AUDIO_COMMAND",
    "GCS_AUDIO_RESPONSE",
    "GCS_AUDIO_TRANSCRIBED",
    "NatsClient",
    "NatsVoiceTransport",
    "PayloadStyle",
    "VOICE_AUDIO_BLOB",
    "VOICE_AUDIO_FRAME",
    "VOICE_COMMAND_WINDOW_CLOSED",
    "VOICE_COMMAND_WINDOW_STARTED",
    "VOICE_CONTROL",
    "VOICE_RECIPIENT_REQUEST",
    "VOICE_RECIPIENT_RESPONSE",
    "VOICE_STATUS",
    "VOICE_TRANSCRIPT_HYPOTHESIS",
    "VOICE_TRANSCRIPT_INTERVAL_FINAL",
    "VOICE_TRANSCRIPT_SEGMENT_FINAL",
    "VOICE_TTS_AUDIO",
    "VOICE_TTS_REQUEST",
    "VOICE_WAKE_DETECTED",
    "audio_blob_from_payload",
    "audio_blob_subject",
    "audio_blob_to_payload",
    "pack_payload",
    "transcript_event_from_payload",
    "transcript_event_to_payload",
    "transcript_subject",
    "tts_audio_from_payload",
    "tts_audio_subject",
    "tts_audio_to_payload",
    "unpack_payload",
    "voice_session_subject",
]
