"""Constructing a Camera must not touch the filesystem for TLS -- cert
generation is deferred to the first actual streaming attempt (see
Camera._ensureSslPath()). This matters for capture-only use in containers,
service accounts, or environments with no usable/writable home directory."""

import stat
import sys
from pathlib import Path

from olab_camera import CameraUSB


def test_camera_construction_does_not_create_ssl_dir(tmp_path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path))
    monkeypatch.setattr(Path, "home", lambda: tmp_path)

    CameraUSB(paramDict={"res_rows": 480, "res_cols": 640, "fps_target": 30})

    default_ssl_dir = tmp_path / ".olab_camera" / "ssl"
    assert not default_ssl_dir.exists()


def test_camera_ssl_path_defaults_without_generating_cert(tmp_path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path))
    monkeypatch.setattr(Path, "home", lambda: tmp_path)

    cam = CameraUSB(paramDict={"res_rows": 480, "res_cols": 640, "fps_target": 30})

    assert cam.sslPath == str(tmp_path / ".olab_camera" / "ssl")
    assert not (tmp_path / ".olab_camera" / "ssl" / "ca.key").exists()


def test_ensure_ssl_path_generates_cert_on_demand(tmp_path, monkeypatch):
    monkeypatch.setenv("HOME", str(tmp_path))
    monkeypatch.setattr(Path, "home", lambda: tmp_path)

    cam = CameraUSB(paramDict={"res_rows": 480, "res_cols": 640, "fps_target": 30})
    assert not (tmp_path / ".olab_camera" / "ssl" / "ca.key").exists()

    cam._ensureSslPath()

    ssl_dir = Path(cam.sslPath)
    assert (ssl_dir / "ca.key").exists()
    assert (ssl_dir / "ca.crt").exists()


def test_explicit_ssl_path_is_never_touched(tmp_path, monkeypatch):
    """A Camera constructed with an explicit sslPath (an administrator- or
    student-supplied certificate directory, possibly root-/group-managed,
    with an encrypted key, a non-RSA key, or a full chain) must never be
    locked, chmod'd, parsed, or regenerated by olab_camera -- only its own
    auto-managed default (~/.olab_camera/ssl) is ever touched."""
    monkeypatch.setenv("HOME", str(tmp_path / "unused-home"))
    monkeypatch.setattr(Path, "home", lambda: tmp_path / "unused-home")

    custom_ssl_dir = tmp_path / "custom-ssl"
    custom_ssl_dir.mkdir(mode=0o750)
    # Deliberately not a real cert/key pair -- proves olab_camera never
    # tries to parse or validate this content itself.
    (custom_ssl_dir / "ca.key").write_bytes(b"not a real private key")
    (custom_ssl_dir / "ca.crt").write_bytes(b"not a real certificate")
    key_before = (custom_ssl_dir / "ca.key").read_bytes()
    cert_before = (custom_ssl_dir / "ca.crt").read_bytes()
    if sys.platform != "win32":
        dir_mode_before = stat.S_IMODE(custom_ssl_dir.stat().st_mode)

    cam = CameraUSB(
        paramDict={"res_rows": 480, "res_cols": 640, "fps_target": 30},
        sslPath=str(custom_ssl_dir),
    )
    assert cam._usesGeneratedTls is False

    cam._ensureSslPath()  # must be a true no-op for an explicit sslPath

    assert cam.sslPath == str(custom_ssl_dir)
    assert (custom_ssl_dir / "ca.key").read_bytes() == key_before
    assert (custom_ssl_dir / "ca.crt").read_bytes() == cert_before
    assert not (custom_ssl_dir / ".generate.lock").exists()
    if sys.platform != "win32":
        assert stat.S_IMODE(custom_ssl_dir.stat().st_mode) == dir_mode_before
    # The auto-managed default directory must not have been created either.
    assert not (tmp_path / "unused-home" / ".olab_camera").exists()
